version: '3'
services:
  issf-world-rankings:
    image: michaelwknott/issf-world-rankings:2.0
    env_file:
      - .env
    depends_on:
      - issf-dev-postgres
  issf-dev-postgres:
    image: postgres
    env_file:
      - .env